import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const screenshotDir='test-results/screenshots';
test('desktop discovery, local account, watchlist persistence, forecast, review, library, export, and deletion',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1000});await page.goto('/');
 await expect(page.locator('.poster-card')).toHaveCount(6);await expect(page.locator('.hero h1')).toHaveText('Beyond the Dunes');
 mkdirSync(screenshotDir,{recursive:true});await page.screenshot({path:`${screenshotDir}/desktop.png`,fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Next spotlight',exact:true}).click();await expect(page.locator('.hero h1')).toHaveText('Neon District');
 await page.getByLabel('Search movies and series').fill('orbit');await expect(page.locator('.poster-card')).toHaveCount(1);await expect(page.locator('.poster-title')).toHaveText('Orbit Nine');
 await page.getByLabel('Clear search').click();await expect(page.locator('.poster-card')).toHaveCount(6);
 await page.getByRole('button',{name:'Series',exact:true}).click();await expect(page.locator('.poster-card')).toHaveCount(2);
 await page.getByRole('button',{name:'Everything',exact:true}).click();await expect(page.locator('.poster-card')).toHaveCount(6);
 await page.getByLabel('Filter by genre').selectOption('Romance');await expect(page.locator('.poster-card')).toHaveCount(1);await page.getByLabel('Filter by genre').selectOption('');
 await page.getByLabel('Sign in',{exact:true}).click();await page.getByRole('button',{name:'Create an account',exact:true}).click();
 const email=`browser-${Date.now()}@example.test`,password='local-test-password-7391';
 await page.getByLabel('Your name',{exact:true}).fill('Cinema Tester');await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.locator('dialog')).toHaveCount(0);
 await page.getByLabel('Save Beyond the Dunes',{exact:true}).click();await expect(page.getByLabel('Remove Beyond the Dunes',{exact:true})).toBeVisible();
 await page.reload();await expect(page.getByLabel('Remove Beyond the Dunes',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Open Beyond the Dunes',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('tab',{name:'Prediction desk'}).click();
 await expect(page.locator('.poll-number')).toContainText('Your call can start');await page.getByRole('button',{name:'Save my forecast',exact:true}).click();await expect(page.locator('.poll-number')).toContainText('100');await expect(page.locator('.poll-labels')).toContainText('1 hit');
 await page.getByRole('button',{name:'Flop',exact:true}).click();await page.getByRole('button',{name:'Update my forecast',exact:true}).click();await expect(page.locator('.poll-labels')).toContainText('1 flop');await expect(page.locator('.poll-number small')).toContainText('1 account');
 await page.getByText('Box-office scenario lab',{exact:false}).click();await page.getByLabel('Production ($m)').fill('100');await page.getByLabel('Marketing ($m)').fill('50');await expect(page.locator('.scenario-result')).toContainText('$300M');
 await page.locator('.modal-scroller').evaluate(el=>{el.scrollTop=0;});
 await page.screenshot({path:`${screenshotDir}/prediction.png`,fullPage:false,animations:'disabled'});
 await page.getByRole('tab',{name:'Community',exact:true}).click();await page.getByLabel('Your first impression',{exact:false}).fill('Thoughtful science fiction is always worth a conversation.');await page.getByRole('button',{name:'Share my take',exact:true}).click();await expect(page.locator('.review-body')).toHaveText('Thoughtful science fiction is always worth a conversation.');
 await page.getByLabel('Close dialog',{exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'My library',exact:true}).click();await expect(page.locator('.poster-card')).toHaveCount(1);
 await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Predictions',exact:true}).click();await page.getByRole('button',{name:'My forecasts',exact:true}).click();await expect(page.locator('.forecast-row')).toHaveCount(1);await expect(page.locator('.forecast-badge')).toContainText('FLOP');
 await page.getByLabel('Open your profile',{exact:true}).click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Export my data',exact:true}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('cinepulse-export.json');
 await page.getByRole('button',{name:'Delete my account',exact:true}).click();await page.getByLabel('Confirm your password').fill(password);await page.getByRole('button',{name:'Permanently delete account',exact:true}).click();await expect(page.locator('dialog')).toHaveCount(0);await expect(page.getByLabel('Sign in',{exact:true})).toBeVisible();
 expect(errors).toEqual([]);
});
test('mobile layout, calendar, empty community, and keyboard dialog dismissal',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('.poster-card')).toHaveCount(6);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 mkdirSync(screenshotDir,{recursive:true});await page.screenshot({path:`${screenshotDir}/mobile.png`,fullPage:true,animations:'disabled'});
 await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'Calendar',exact:true}).click();await expect(page.locator('.calendar-row')).toHaveCount(6);await page.locator('.calendar-row').first().click();await expect(page.locator('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('dialog')).toHaveCount(0);
 await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'Community',exact:true}).click();await expect(page.getByText('A good conversation starts with one person.')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
