'use client';
import {useState} from 'react';
import {ArrowRight,Download,Eye,EyeOff,LogOut,ShieldCheck,Trash2,UserRound} from 'lucide-react';
import {api} from './client';
import {useApp} from './Context';
import {ErrorBox,Logo,Modal} from './UI';
export function AuthDialog({onClose}:{onClose:()=>void}){
 const {refresh,toast}=useApp();const [register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{await api(`/auth/${register?'register':'login'}`,'POST',{name:form.get('name'),email:form.get('email'),password:form.get('password')});await refresh();toast(register?'Welcome to your next chapter.':'Good to have you back.');onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal label={register?'Create your account':'Sign in to Cinepulse'} onClose={onClose}><div className="auth"><Logo/><span className="eyebrow mint">YOUR OWN LITTLE CORNER OF CINEMA</span><h2>{register?'Good taste deserves\na home.':'Welcome back,\nfilm person.'}</h2><p>{register?'Save the stories you love. Discover the ones you will.':'Your watchlist and your opening-night calls are waiting.'}</p><form onSubmit={submit} aria-busy={busy} aria-describedby={error?'auth-form-error':undefined}>{register&&<label>Your name<input name="name" autoComplete="name" required minLength={2} maxLength={60} placeholder="What should we call you?" disabled={busy}/></label>}<label>Email address<input type="email" name="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" disabled={busy}/></label><label>Password<div className="password-field"><input type={visible?'text':'password'} name="password" autoComplete={register?'new-password':'current-password'} required minLength={register?10:1} maxLength={128} placeholder={register?'At least 10 characters':'Your password'} disabled={busy}/><button type="button" disabled={busy} onClick={()=>setVisible(!visible)} aria-label={visible?'Hide password':'Show password'}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<div id="auth-form-error"><ErrorBox message={error}/></div>}<button className="button primary full" disabled={busy}>{busy?'One moment…':register?'Create account':'Sign in'} <ArrowRight size={17}/></button></form><p className="auth-switch">{register?'Already part of the club?':'New to Cinepulse?'} <button disabled={busy} onClick={()=>{setRegister(!register);setError('');}}>{register?'Sign in':'Create an account'}</button></p><div className="privacy-note"><ShieldCheck size={16}/><span>Stored in this local installation. No email is sent. Password recovery is not available in this local version—use a password manager.</span></div></div></Modal>;
}
export function ProfileDialog({onClose}:{onClose:()=>void}){
 const {user,library,refresh,toast}=useApp();const [deleting,setDeleting]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function logout(){setBusy(true);try{await api('/auth/logout','POST');await refresh();onClose();toast('You are signed out.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/account','DELETE',{password});await refresh();onClose();toast('Your account and its data have been deleted.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal label="Your profile" onClose={onClose}><div className="profile"><div className="profile-avatar">{user?.name.slice(0,1).toUpperCase()}</div><span className="eyebrow mint">THE PERSON BEHIND THE PICKS</span><h2>{user?.name}</h2><p>{user?.email}</p><div className="profile-stats"><div><strong>{library.length}</strong><span>In your library</span></div><div><strong>{library.filter(x=>x.status==='watched').length}</strong><span>Watched</span></div><div><strong>{library.filter(x=>x.rating!==null).length}</strong><span>Rated</span></div></div><a className="button secondary full" href="/api/export" download aria-disabled={busy?'true':undefined}><Download size={17}/> Export my data</a><button className="button secondary full" onClick={logout} disabled={busy}><LogOut size={17}/> {busy?'Signing out…':'Sign out'}</button><div className="privacy-note"><UserRound size={18}/><span>Your watchlist is private. Your display name and reviews are public within this installation. Forecasts contribute to anonymous aggregate counts.</span></div>{error&&<div id="profile-form-error"><ErrorBox message={error}/></div>}<button className="danger-link" disabled={busy} onClick={()=>setDeleting(!deleting)}><Trash2 size={15}/> Delete my account</button>{deleting&&<form onSubmit={remove} className="delete-account" aria-busy={busy} aria-describedby={error?'profile-form-error':undefined}><p>This permanently deletes your library, reviews, forecasts, and account. This cannot be undone.</p><label>Confirm your password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy} required/></label><button className="button danger full" disabled={busy}>{busy?'Deleting…':'Permanently delete account'}</button></form>}</div></Modal>;
}
