(() => {
'use strict';
const films = window.CINEPULSE_CATALOG;
const samples = window.CINEPULSE_IMPRESSIONS;
const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sqlText = value => `'${String(value).replaceAll("'", "''")}'`;
const paths = {
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',
 'arrow-up-right':'<path d="M7 17 17 7M7 7h10v10"/>',
 'arrow-right':'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 plus:'<path d="M12 5v14M5 12h14"/>', check:'<path d="m5 12 4 4L19 6"/>',
 bookmark:'<path d="M6 4h12v17l-6-4-6 4V4Z"/>',
 activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',
 sparkles:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Zm7-2v4m-2-2h4"/>',
 trend:'<path d="m3 17 6-6 4 4 8-10m-6 0h6v6"/>',
 users:'<path d="M3 21v-2a5 5 0 0 1 5-5h3a5 5 0 0 1 5 5v2m2-7a5 5 0 0 1 3 5v2"/><circle cx="9.5" cy="6.5" r="3.5"/><path d="M16 3a3.5 3.5 0 0 1 0 7"/>',
 compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6 6-2Z"/>',
 x:'<path d="m6 6 12 12M6 18 18 6"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',
 eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 star:'<path d="m12 3 2.8 5.8 6.4.9-4.6 4.5 1.1 6.3L12 17.5l-5.7 3 1.1-6.3-4.6-4.5 6.4-.9L12 3Z"/>',
 chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2 1.8-6A8.5 8.5 0 1 1 21 11.5Z"/>',
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
 film:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 3v18M17 3v18M3 8h4m-4 8h4M17 8h4m-4 8h4"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
 feather:'<path d="M20 4c-5-5-16 6-13 13s18-8 13-13ZM3 21 15 9M7 17h7"/>',
 sliders:'<path d="M4 7h5m4 0h7M4 17h9m4 0h3"/><circle cx="11" cy="7" r="2"/><circle cx="15" cy="17" r="2"/>'
};
function icon(name, fill=false){return `<svg viewBox="0 0 24 24" fill="${fill?'currentColor':'none'}" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.film}</svg>`;}
function hydrateIcons(parent=document){$$('[data-icon]',parent).forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
const state={nav:'discover',query:'',genre:'All',type:'All',sort:'score',hero:0,saved:new Set(),votes:{},posts:[],ready:false,storage:'loading',selected:null,rating:4};
let toastTimer, lastFocus, writeQueue=Promise.resolve();
function toast(text){const node=$('#toast');node.textContent=text;node.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('visible'),3500);}
function filmById(id){return films.find(f=>f.id===id);}
function monthDate(date){return new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'});}
function shortDate(date){return new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',year:'numeric'});}
function probabilityLabel(f){return f.score>=85?'Breakout potential':f.score>=75?'Strong potential':f.score>=65?'One to watch':'Mixed signals';}
function stars(n){return '★'.repeat(n)+'☆'.repeat(5-n);}
function ring(f){return `<div class="score-ring" aria-label="Simulated success probability ${f.score} percent"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="44" stroke="rgba(255,255,255,.13)" fill="none" stroke-width="4"/><circle cx="50" cy="50" r="44" stroke="${f.score<65?'#edc391':'#c3f6cd'}" fill="none" stroke-width="4" stroke-linecap="round" stroke-dasharray="${f.score*2.765} 276.5"/></svg><strong>${f.score}<small>%</small></strong></div>`;}
function sparkline(f,large=false){const points=f.trend.map((v,i)=>`${i*10},${100-v}`).join(' ');return `<svg class="${large?'forecast-chart':'sparkline'}" viewBox="0 0 110 80" preserveAspectRatio="none" role="img" aria-label="Simulated interest trend for ${escapeHTML(f.title)}"><path d="M0 60H110M0 30H110" stroke="rgba(255,255,255,.05)" stroke-width=".6" fill="none"/><polyline points="${points}" fill="none" stroke="${f.change<0?'#edc391':'#a6deb7'}" stroke-width="${large?1.4:2}" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
function typeSwitch(){return `<div class="type-switch" role="group" aria-label="Title type">${['All','Movie','Series'].map(type=>`<button data-type="${type}" class="${state.type===type?'active':''}" aria-pressed="${state.type===type}">${type==='All'?'Everything':type==='Movie'?'Movies':'Series'}</button>`).join('')}</div>`;}
function filters(){return `<div class="filters" role="group" aria-label="Filter by genre">${['All','Sci-Fi','Thriller','Drama','Romance','Action'].map(g=>`<button data-genre="${g}" class="chip ${state.genre===g?'active':''}" aria-pressed="${state.genre===g}">${g}</button>`).join('')}</div>`;}
function filtered(onlySaved=false){return films.filter(f=>(!onlySaved||state.saved.has(f.id))&&(state.type==='All'||state.type===f.type)&&(state.genre==='All'||f.genres.includes(state.genre))&&(!state.query||`${f.title} ${f.genres.join(' ')} ${f.director}`.toLowerCase().includes(state.query.toLowerCase())));}
function saveButton(f,poster=false){const saved=state.saved.has(f.id);return `<button data-save="${f.id}" class="${poster?'save-poster':'button secondary'} ${saved?'saved':''}" aria-label="${saved?'Remove '+escapeHTML(f.title)+' from':'Add '+escapeHTML(f.title)+' to'} watchlist" aria-pressed="${saved}" ${!state.ready?'disabled':''}>${icon(saved?'check':poster?'plus':'bookmark')}${poster?'':saved?'In watchlist':'Watchlist'}</button>`;}
function movieCard(f){return `<article class="movie-card"><div class="poster"><img src="${f.image}" alt="Original concept artwork for ${escapeHTML(f.title)}" loading="lazy" width="360" height="540"><button data-film="${f.id}" class="poster-open" aria-label="Explore ${escapeHTML(f.title)}"><span class="poster-badge ${f.score<65?'caution':''}">${icon('trend')}${f.score}% <span>potential</span></span><span class="poster-wordmark ${f.color}">${f.display}<span class="poster-caption">A CINEPULSE CONCEPT</span></span></button>${saveButton(f,true)}</div><button class="movie-name" data-film="${f.id}">${f.title}</button><div class="movie-meta"><span>${shortDate(f.date)} <span aria-hidden="true">·</span> ${f.genres[0]}</span><span class="movie-type">${f.type==='Series'?'SERIES':'FILM'}</span></div></article>`;}
function emptyState(saved=false){const hasFilters=state.query||state.genre!=='All'||state.type!=='All';return `<div class="empty-state">${icon(saved?'bookmark':'search')}<h2>${hasFilters?'Nothing in this frame.':saved?'Your next favorites belong here.':'More stories are on their way.'}</h2><p>${hasFilters?'Try another title, or clear your filters.':'Tap the + on any poster to build your own watchlist.'}</p><button class="button primary" ${hasFilters?'data-reset':'data-nav="discover"'}>${hasFilters?'Clear filters':'Discover something good'} ${icon('arrow-right')}</button></div>`;}
function hero(){const candidates=films.filter(f=>state.type==='All'?['dunes','neon','orbit'].includes(f.id):f.type===state.type);const f=candidates[state.hero%candidates.length];return `<section class="hero" aria-label="Featured concept: ${f.title}"><img class="hero-image" src="${f.hero}" alt="${f.title} cinematic concept artwork" fetchpriority="high"><div class="hero-shade"></div><div class="hero-content"><div class="hero-kicker">${icon('sparkles')} THE SPOTLIGHT <span class="mini-label">COMING ${shortDate(f.date).toUpperCase()} · DEMO</span></div><div><h2 class="hero-title">${f.display}</h2><div class="hero-meta"><span>2027</span><span>${f.genres.join(' / ')}</span><span>${f.runtime}</span></div><p class="hero-tagline">${f.tagline}</p><div class="hero-buttons"><button class="button primary" data-film="${f.id}">Explore ${f.type==='Series'?'series':'film'} ${icon('arrow-up-right')}</button>${saveButton(f)}</div><div class="hero-bottom"><span>0${state.hero%candidates.length+1} / 0${candidates.length}</span><div class="hero-dots">${candidates.map((c,i)=>`<button data-hero="${i}" class="${state.hero%candidates.length===i?'active':''}" aria-label="Feature ${c.title}" aria-pressed="${state.hero%candidates.length===i}"></button>`).join('')}</div><span>STORIES WORTH THE WAIT</span></div></div></div><aside class="hero-forecast glass"><div class="forecast-top"><span>${icon('activity')} THE PULSE</span><span class="preview-label">SIMULATED</span></div><div class="hero-score">${ring(f)}<div class="score-caption"><strong>${probabilityLabel(f)}</strong><span>Success probability</span><span class="positive">${f.change>0?'+':''}${f.change} pts this week</span></div></div><div class="signals-group"><div class="signal-mini"><span>Audience interest</span><b>${f.interest}%</b></div><div class="signal-mini"><span>Conversation pace</span><b>${f.pace}</b></div></div><button class="forecast-link" data-forecast="${f.id}">Explore the forecast ${icon('arrow-up-right')}</button></aside></section>`;}
function compactRow(f,index){return `<div class="compact-row"><span class="rank">0${index+1}</span><img src="${f.image}" alt="" loading="lazy"><button class="compact-info" data-forecast="${f.id}"><strong>${f.title}</strong><span>${f.type} · ${shortDate(f.date)}</span></button>${sparkline(f)}<span class="compact-score"><strong>+${f.change}</strong><small>points this week</small></span></div>`;}
function miniReview(review,full=false){const f=filmById(review.film);if(!f)return '';return `<div class="mini-review"><span class="person-avatar ${review.color||'mint'}">${escapeHTML(review.initial||'R')}</span><div class="mini-review-body"><div class="review-byline"><strong>${escapeHTML(review.name||'Rey')}</strong><span>${review.id.startsWith('sample')?'· sample member':'· your preview'}</span><span class="stars" aria-label="Anticipation ${review.rating} out of 5">${stars(review.rating)}</span></div><p>${escapeHTML(review.text)}</p><div class="review-film">Anticipating <button data-film="${f.id}">${f.title} ${icon('arrow-up-right')}</button></div>${full?`<div class="review-actions"><span>${icon('chat')} First impression, not a review</span><span>${review.ago||'Just added'}</span></div>`:''}</div></div>`;}
function discover(){const list=filtered();return `<div class="page-intro"><div><h1>Cinema, ahead of the curve.</h1><p>Discover your next obsession. Call the next big hit.</p></div>${typeSwitch()}</div>${!state.query?hero():''}<div class="context-strip"><div>${icon('activity')}<span><strong>A little instinct. A little insight.</strong> Forecasts are simulated in this preview.</span></div><button class="text-button" data-method>How the pulse works ${icon('arrow-up-right')}</button></div><section aria-labelledby="radar-heading"><div class="section-header"><div><h2 id="radar-heading">${state.query?'In the searchlight':'On our radar'}</h2><p>${state.query?`${list.length} ${list.length===1?'match':'matches'} for “${escapeHTML(state.query)}”`:'Tomorrow’s conversations start here.'}</p></div>${filters()}</div><div class="poster-grid">${list.length?list.map(movieCard).join(''):emptyState()}</div></section>${!state.query?`<div class="lower-grid"><section class="insight-panel"><div class="section-header"><div><h2>${icon('trend')} Gaining momentum</h2><p>The biggest movers in our demo universe.</p></div><button class="text-button" data-nav="predictions">View all ${icon('arrow-up-right')}</button></div>${[...films].sort((a,b)=>b.change-a.change).slice(0,3).map(compactRow).join('')}</section><section class="insight-panel"><div class="section-header"><div><h2>${icon('chat')} The conversation</h2><p>Good films start a conversation. So do good instincts.</p></div><button class="text-button" data-nav="community">Join in ${icon('arrow-up-right')}</button></div>${samples.slice(0,2).map(r=>miniReview(r)).join('')}</section></div>`:''}`;}
function board(){const list=filtered().sort(state.sort==='date'?(a,b)=>a.date.localeCompare(b.date):state.sort==='name'?(a,b)=>a.title.localeCompare(b.title):(a,b)=>b.score-a.score);return `<div class="page-heading"><div class="eyebrow">${icon('activity')} THE FORECAST ROOM</div><div class="heading-row"><div><h1>Make the call. Before the crowd.</h1><p>A closer look at the stories with breakout potential.</p></div><button class="button ghost" data-method>${icon('info')} Behind the numbers</button></div></div><div class="notice">${icon('info')}<div><strong>A design preview, not a prediction engine.</strong> Every score, signal, and trend below is simulated. Film and series success require different definitions; these demo scores are not validated or comparable real-world forecasts.</div></div><div class="board-controls">${typeSwitch()}<label><span class="eyebrow" style="position:absolute;clip:rect(0,0,0,0)">Sort forecasts</span><select class="sort-select" id="forecast-sort" aria-label="Sort forecasts"><option value="score" ${state.sort==='score'?'selected':''}>Highest potential</option><option value="date" ${state.sort==='date'?'selected':''}>Release date</option><option value="name" ${state.sort==='name'?'selected':''}>Title A–Z</option></select></label></div><div class="prediction-list">${list.length?list.map((f,i)=>`<article class="prediction-row"><span class="rank">${String(i+1).padStart(2,'0')}</span><img src="${f.image}" alt="${f.title} concept poster"><div><button class="prediction-title" data-forecast="${f.id}">${f.title}</button><div class="prediction-sub">${f.type} · ${f.genres[0]} · ${monthDate(f.date)}, 2027</div></div><div class="board-signal"><div class="bar-label"><span>Audience interest</span><span>${f.interest}%</span></div><div class="bar-track"><i style="width:${f.interest}%"></i></div></div>${sparkline(f)}<div><div class="board-score ${f.score<65?'caution':''}">${f.score}<small>%</small></div><div class="score-label">SIMULATED POTENTIAL</div></div><button class="button ghost" data-forecast="${f.id}">The signals ${icon('arrow-up-right')}</button></article>`).join(''):emptyState()}</div><p class="data-disclaimer">Illustrative release calendar: 2027. Community votes are saved separately and do not recalculate the demo forecasts.</p>`;}
function watchlist(){const list=filtered(true);return `<div class="page-heading"><div class="eyebrow">${icon('bookmark')} YOUR PERSONAL REEL</div><div class="heading-row"><div><h1>Worth the wait.</h1><p>${state.saved.size} ${state.saved.size===1?'story':'stories'} saved. A little collection of your next obsessions.</p></div><button class="button ghost" data-export>${icon('arrow-up-right')} Export watchlist</button></div></div><div class="board-controls">${typeSwitch()}${filters()}</div><div class="poster-grid">${list.length?list.map(movieCard).join(''):emptyState(true)}</div><p class="data-disclaimer">${storageNote()} · Your watchlist is private to this preview space.</p>`;}
function community(){return `<div class="page-heading"><div class="eyebrow">${icon('users')} THE COMMON ROOM</div><div class="heading-row"><div><h1>Good taste loves company.</h1><p>First impressions. Wild theories. That one film you can’t stop thinking about.</p></div><button class="button primary" data-compose ${!state.ready?'disabled':''}>${icon('feather')} Add your take</button></div></div><div class="notice">${icon('info')}<div>Sample members and conversations are fictional. Your takes stay in this preview; they are not published to a live social network. Stars show <strong>anticipation</strong>, not post-release ratings.</div></div><div class="community-layout"><div class="community-feed">${[...state.posts,...samples].map(r=>`<article class="review-card">${miniReview(r,true)}</article>`).join('')}</div><aside class="community-side insight-panel"><div class="eyebrow" style="padding-bottom:13px">A SEAT FOR EVERY OPINION</div><h3>Your gut has a point of view.</h3><p>Open a title, explore its concept, and tell us if you’re in. There’s more to a film than the numbers.</p><button class="button secondary" data-nav="discover">Find your next obsession ${icon('arrow-right')}</button><div class="rule-list"><div>${icon('heart')} Critique the work. Respect the person.</div><div>${icon('eye')} First impressions, without pretending you’ve seen it.</div><div>${icon('shield')} Your preview posts stay private.</div></div></aside></div>`;}
function render(){const main=$('#main');main.innerHTML=state.nav==='discover'?discover():state.nav==='predictions'?board():state.nav==='watchlist'?watchlist():community();$$('[data-nav]').forEach(b=>{const active=b.dataset.nav===state.nav;b.classList.toggle('active',active);if(b.closest('nav'))b.setAttribute('aria-current',active?'page':'false');});$$('.saved-count').forEach(el=>el.textContent=state.saved.size);}
function navigate(nav){if(!['discover','predictions','community','watchlist'].includes(nav))return;state.nav=nav;state.genre='All';state.type='All';state.query='';$('#search-input').value='';render();window.scrollTo({top:0,behavior:'instant'});}
function storageNote(){return state.storage==='bridge'?'Saved in this Tasklet thread':state.storage==='local'?'Saved in this browser':state.storage==='loading'?'Loading your space…':'Session only — persistent storage unavailable';}
function serializeState(){return {saved:[...state.saved],votes:state.votes,posts:state.posts};}
function persist(sql){const snapshot=JSON.stringify(serializeState());const task=async()=>{if(state.storage==='bridge')await window.tasklet.sqlExec(sql);else if(state.storage==='local')localStorage.setItem('cinepulse-preview-v1',snapshot);else throw new Error('Persistent storage unavailable');};const promise=writeQueue.then(task);writeQueue=promise.catch(()=>{});return promise;}
async function initStorage(){try{if(window.tasklet?.sqlQuery && window.tasklet?.sqlExec){state.storage='bridge';await Promise.all([
window.tasklet.sqlExec('CREATE TABLE IF NOT EXISTS cinepulse_watchlist (film_id TEXT PRIMARY KEY)'),
window.tasklet.sqlExec('CREATE TABLE IF NOT EXISTS cinepulse_votes (film_id TEXT PRIMARY KEY, choice TEXT NOT NULL)'),
window.tasklet.sqlExec('CREATE TABLE IF NOT EXISTS cinepulse_impressions (id TEXT PRIMARY KEY, film_id TEXT NOT NULL, body TEXT NOT NULL, rating INTEGER NOT NULL, created_at TEXT NOT NULL)')]);
const [saved,votes,posts]=await Promise.all([window.tasklet.sqlQuery('SELECT film_id FROM cinepulse_watchlist'),window.tasklet.sqlQuery('SELECT film_id, choice FROM cinepulse_votes'),window.tasklet.sqlQuery('SELECT id, film_id, body, rating, created_at FROM cinepulse_impressions ORDER BY created_at DESC')]);
state.saved=new Set(saved.filter(r=>filmById(r.film_id)).map(r=>r.film_id));state.votes=Object.fromEntries(votes.filter(r=>filmById(r.film_id)&&['yes','no'].includes(r.choice)).map(r=>[r.film_id,r.choice]));state.posts=posts.filter(r=>filmById(r.film_id)).map(r=>({id:r.id,film:r.film_id,text:r.body,rating:Math.max(1,Math.min(5,Number(r.rating)||1)),name:'Rey',initial:'R',color:'mint',ago:'Your saved take'}));
}else{state.storage='local';const raw=localStorage.getItem('cinepulse-preview-v1');if(raw){const parsed=JSON.parse(raw);state.saved=new Set((parsed.saved||[]).filter(id=>filmById(id)));state.votes=parsed.votes||{};state.posts=(parsed.posts||[]).filter(r=>filmById(r.film));}localStorage.setItem('cinepulse-preview-v1',JSON.stringify(serializeState()));}}
catch(error){console.error('Cinepulse could not load persistent storage',error);state.storage='session';toast('Storage unavailable. You can browse; changes are session-only.');}finally{state.ready=true;render();}}
async function toggleSave(id){if(!state.ready)return;const film=filmById(id);if(!film)return;const previouslySaved=state.saved.has(id);if(previouslySaved)state.saved.delete(id);else state.saved.add(id);render();refreshSaveButtons();if(state.storage==='session'){toast(previouslySaved?'Removed for this session':'Added for this session only');return;}try{await persist(previouslySaved?`DELETE FROM cinepulse_watchlist WHERE film_id=${sqlText(id)}`:`INSERT OR IGNORE INTO cinepulse_watchlist (film_id) VALUES (${sqlText(id)})`);toast(previouslySaved?'Removed from your watchlist':`${film.title} is on your watchlist`);}catch(error){console.error('Watchlist save failed',error);if(previouslySaved)state.saved.add(id);else state.saved.delete(id);render();refreshSaveButtons();toast('Couldn’t save that change. Please try again.');}}
function refreshSaveButtons(){if($('#detail-dialog').open&&state.selected){$$('[data-save]', $('#dialog-body')).forEach(button=>{button.outerHTML=saveButton(filmById(button.dataset.save));});}}
function openDialog(html){lastFocus=document.activeElement;$('#dialog-body').innerHTML=html;const dialog=$('#detail-dialog');if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('#close-dialog').focus();}
function closeDialog(){const dialog=$('#detail-dialog');dialog.close();state.selected=null;if(lastFocus?.isConnected)lastFocus.focus();else $('#main').focus({preventScroll:true});}
function pollMarkup(f){const v=state.votes[f.id];return `<div class="poll"><div><h3>What’s your instinct?</h3><p>${v?(v==='yes'?'You’re calling a hit.':'You’re not convinced.'): 'Make your own call. There’s no wrong first impression.'}</p></div><div class="poll-buttons"><button class="poll-button ${v==='yes'?'selected':''}" data-vote="yes" data-id="${f.id}" aria-pressed="${v==='yes'}" ${!state.ready?'disabled':''}>${icon('trend')} Calling a hit</button><button class="poll-button ${v==='no'?'selected':''}" data-vote="no" data-id="${f.id}" aria-pressed="${v==='no'}" ${!state.ready?'disabled':''}>${icon('eye')} Not convinced</button></div></div>`;}
function openFilm(id,forecast=false){const f=filmById(id);if(!f)return;state.selected=id;openDialog(`<div class="dialog-hero"><img src="${f.hero}" alt="${f.title} concept artwork"><div class="dialog-hero-text"><div class="eyebrow">ORIGINAL FICTIONAL CONCEPT · ${f.type.toUpperCase()}</div><h2 id="dialog-title">${f.title}</h2></div></div><div class="dialog-content"><div class="detail-actions"><div class="hero-meta"><span>${monthDate(f.date)}, 2027</span><span>${f.genres.join(' / ')}</span><span>${f.runtime}</span></div>${saveButton(f)}</div><p class="detail-description">${f.description}</p><div class="detail-section-title" id="forecast-detail">The pulse behind the picture <span>SIMULATED DATA</span></div><div class="forecast-detail"><div>${ring(f)}<div class="score-caption"><strong>${probabilityLabel(f)}</strong><span>Illustrative probability</span></div></div><div>${['Audience interest','Conversation sentiment','Release positioning'].map((label,i)=>`<div class="signal-bar"><div class="bar-label"><span>${label}</span><span>${f.signals[i]} / 100</span></div><div class="bar-track"><i style="width:${f.signals[i]}%"></i></div></div>`).join('')}${sparkline(f,true)}<div class="chart-labels"><span>Illustrative 12-week trend</span><span>Preview point</span></div></div></div><p class="data-disclaimer">All values are handcrafted interface examples—not API measurements, statistical confidence, or trained-model predictions. No real trailer or social-media data is used. ${f.type==='Series'?'Series success needs a separate audience or renewal target, not a box-office label.':'A production forecast needs a defined financial target, reliable costs and box-office labels.'} <button class="text-button" data-method>Read the methodology ${icon('arrow-up-right')}</button></p><div class="detail-section-title">Your call, not the crowd’s.</div><div id="poll-region">${pollMarkup(f)}</div><p class="data-disclaimer">Your choice stays in this preview and does not alter the simulated forecast.</p><div class="detail-section-title">Start the conversation <button class="text-button" data-compose="${f.id}">Add your take ${icon('feather')}</button></div><p class="detail-description">${f.tagline} What about this premise has you curious?</p></div>`);if(forecast)requestAnimationFrame(()=>$('#forecast-detail').scrollIntoView({block:'start',behavior:'instant'}));}
async function vote(id,choice){if(!state.ready||!filmById(id)||!['yes','no'].includes(choice))return;const previous=state.votes[id];state.votes[id]=choice;$('#poll-region').innerHTML=pollMarkup(filmById(id));if(state.storage==='session'){toast('Your call is saved for this session only.');return;}try{await persist(`INSERT OR REPLACE INTO cinepulse_votes (film_id,choice) VALUES (${sqlText(id)},${sqlText(choice)})`);toast('Your call is in. You can change your mind anytime.');}catch(error){console.error('Prediction vote could not be saved',error);if(previous)state.votes[id]=previous;else delete state.votes[id];if($('#poll-region'))$('#poll-region').innerHTML=pollMarkup(filmById(id));toast('Couldn’t save your call. Try again.');}}
function openMethod(){state.selected=null;openDialog(`<div class="simple-dialog"><div class="eyebrow">${icon('activity')} BEHIND THE PULSE</div><h2 id="dialog-title">More transparency.<br>Less crystal ball.</h2><p>Cinepulse is a frontend concept for discovering films, collecting favorites, and exploring pre-release forecasts. This version uses six fictional titles, original AI-generated artwork, and handcrafted demo numbers.</p><div class="notice">${icon('info')}<div><strong>No prediction model or movie API is connected.</strong> Scores are not calculated from the displayed signal bars. No trailer views, comments, sentiment, community totals, or release dates here are real measurements.</div></div><div class="method-cards"><div class="method-card"><span>01</span><div><h3>Define what “success” means.</h3><p>For films, choose an explicit box-office or profitability target with reliable cost data. Series need a different target, such as audience reach or renewal. Do not compare them as if they were the same.</p></div></div><div class="method-card"><span>02</span><div><h3>Use signals you’re allowed to use.</h3><p>Connect a licensed catalog and use your own audience polls first. Trailer and social APIs have restrictions; YouTube data cannot simply be mixed into a model without checking the applicable permissions.</p></div></div><div class="method-card"><span>03</span><div><h3>Measure before you promise.</h3><p>Train on past releases, test on later releases, and publish accuracy, uncertainty, and dated forecast snapshots. A good-looking percentage is not evidence of a good prediction.</p></div></div></div><p class="data-disclaimer">Working in this preview: navigation, search, filters, sorting, private watchlists, personal predictions, anticipation ratings, and export. Not included: live trailers, authentication, a real public community, streaming, API integration, or a trained forecasting service.</p></div>`);}
function openProfile(){state.selected=null;openDialog(`<div class="simple-dialog"><div class="profile-heading"><div class="avatar" aria-hidden="true">R</div><div><h2 id="dialog-title">Your little cinema club.</h2><p>Rey’s preview space · No login required</p></div></div><div class="profile-stats"><div><strong>${state.saved.size}</strong><span>On your watchlist</span></div><div><strong>${Object.keys(state.votes).length}</strong><span>Calls made</span></div><div><strong>${state.posts.length}</strong><span>First impressions</span></div></div><p>${storageNote()}. This is a single preview space, not a production user account. In Tasklet, saved items belong to this thread; standalone copies use the current browser.</p><button class="button primary" data-go-watchlist>Open my watchlist ${icon('arrow-right')}</button></div>`);}
function openComposer(id){if(!state.ready){toast('Your preview space is still loading.');return;}state.selected=null;state.rating=4;const selected=filmById(id)?id:films[0].id;openDialog(`<div class="simple-dialog"><div class="eyebrow">${icon('feather')} A FIRST IMPRESSION</div><h2 id="dialog-title">What’s your take?</h2><p>A premise, a mood, a wild theory. Tell us what caught your eye.</p><form id="impression-form"><div class="form-field"><label for="impression-film">The story on your mind</label><select id="impression-film">${films.map(f=>`<option value="${f.id}" ${f.id===selected?'selected':''}>${f.title}</option>`).join('')}</select></div><div class="form-field"><label>How much are you anticipating it?</label><div class="rating-input" role="group" aria-label="Anticipation rating">${[1,2,3,4,5].map(n=>`<button type="button" data-rating="${n}" class="${n<=state.rating?'filled':''}" aria-label="${n} out of 5 stars" aria-pressed="${state.rating===n}">${icon('star',n<=state.rating)}</button>`).join('')}</div></div><div class="form-field"><label for="impression-text">Your first impression</label><textarea id="impression-text" placeholder="That premise has me thinking…" required minlength="8" maxlength="500"></textarea><div class="form-help"><span>At least 8 characters. Kindness is good taste.</span><span id="character-count">0 / 500</span></div></div><div class="form-submit"><span>Private preview only. Nothing is published externally.</span><button class="button primary" type="submit">Save my take ${icon('arrow-up-right')}</button></div></form></div>`);}
async function submitImpression(event){event.preventDefault();const body=$('#impression-text').value.trim();if(body.length<8){toast('Give your take at least 8 characters.');$('#impression-text').focus();return;}const film=$('#impression-film').value;const id=`take-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const post={id,film,text:body,rating:state.rating,name:'Rey',initial:'R',color:'mint',ago:'Just added'};state.posts.unshift(post);closeDialog();state.nav='community';render();if(state.storage==='session'){toast('Your take is saved for this session only.');return;}try{await persist(`INSERT INTO cinepulse_impressions (id,film_id,body,rating,created_at) VALUES (${sqlText(id)},${sqlText(film)},${sqlText(body)},${post.rating},${sqlText(new Date().toISOString())})`);toast('Your take is saved. Welcome to the conversation.');}catch(error){console.error('First impression could not be saved',error);state.posts=state.posts.filter(p=>p.id!==id);render();openComposer(film);$('#impression-text').value=body;state.rating=post.rating;paintRating();$('#character-count').textContent=`${body.length} / 500`;toast('Couldn’t save. Your draft is here—please try again.');}}
function paintRating(){$$('[data-rating]').forEach(b=>{const n=Number(b.dataset.rating);b.classList.toggle('filled',n<=state.rating);b.setAttribute('aria-pressed',String(n===state.rating));b.innerHTML=icon('star',n<=state.rating);});}
function exportWatchlist(){const selected=films.filter(f=>state.saved.has(f.id));if(!selected.length){toast('Add a title to your watchlist first.');return;}const text=['CINEPULSE — MY WATCHLIST','Fictional demo titles. Dates and forecasts are simulated.','',...selected.map(f=>`${f.title} | ${f.type} | ${f.genres.join(', ')} | Demo release ${f.date}`)].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='cinepulse-watchlist.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Your watchlist download is ready.');}
function toggleSearch(force){const tray=$('#search-tray');const open=typeof force==='boolean'?force:tray.hidden;tray.hidden=!open;$('#search-toggle').setAttribute('aria-expanded',String(open));if(open)$('#search-input').focus();else{state.query='';$('#search-input').value='';render();}}
document.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;
if(target.dataset.nav){navigate(target.dataset.nav);return;}
if(target.hasAttribute('data-save')){toggleSave(target.dataset.save);return;}
if(target.dataset.film){openFilm(target.dataset.film);return;}
if(target.dataset.forecast){openFilm(target.dataset.forecast,true);return;}
if(target.hasAttribute('data-hero')){state.hero=Number(target.dataset.hero);render();return;}
if(target.dataset.type){state.type=target.dataset.type;state.hero=0;render();return;}
if(target.dataset.genre){state.genre=target.dataset.genre;render();return;}
if(target.hasAttribute('data-reset')){state.genre='All';state.type='All';state.query='';$('#search-input').value='';render();return;}
if(target.hasAttribute('data-method')){openMethod();return;}
if(target.dataset.vote){vote(target.dataset.id,target.dataset.vote);return;}
if(target.hasAttribute('data-compose')){openComposer(target.dataset.compose);return;}
if(target.hasAttribute('data-rating')){state.rating=Number(target.dataset.rating);paintRating();return;}
if(target.hasAttribute('data-export')){exportWatchlist();return;}
if(target.hasAttribute('data-go-watchlist')){closeDialog();navigate('watchlist');}
});
$('#search-toggle').addEventListener('click',()=>toggleSearch());$('#clear-search').addEventListener('click',()=>{state.query='';$('#search-input').value='';render();$('#search-input').focus();});$('#search-input').addEventListener('input',event=>{state.query=event.target.value;state.nav='discover';render();});$('#profile-button').addEventListener('click',openProfile);$('#about-button').addEventListener('click',openMethod);$('#close-dialog').addEventListener('click',closeDialog);
$('#detail-dialog').addEventListener('click',event=>{if(event.target===$('#detail-dialog')){const box=event.target.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)closeDialog();}});
$('#detail-dialog').addEventListener('cancel',event=>{event.preventDefault();closeDialog();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#detail-dialog').open)toggleSearch(false);});document.addEventListener('change',event=>{if(event.target.id==='forecast-sort'){state.sort=event.target.value;render();}});document.addEventListener('input',event=>{if(event.target.id==='impression-text')$('#character-count').textContent=`${event.target.value.length} / 500`;});document.addEventListener('submit',event=>{if(event.target.id==='impression-form')submitImpression(event);});
hydrateIcons();render();initStorage();
})();
