// Original, fictional demo catalog. No real API data or trained-model output.
window.CINEPULSE_CATALOG = [
  {id:'dunes',title:'Beyond the Dunes',display:'BEYOND<br>THE DUNES',type:'Movie',genres:['Sci-Fi','Adventure'],date:'2027-11-19',runtime:'2h 38m',image:'./assets/dunes.webp',hero:'./assets/hero.webp',color:'amber',tagline:'Some worlds are not meant to be found.',description:'When the sun begins to disappear, a lone cartographer crosses an endless desert to find the civilization that learned to live without it. An original fictional epic about memory, survival, and the worlds we leave behind.',score:86,change:12,signals:[91,84,78],interest:92,discussion:'24.8K',pace:'+18%',director:'Ari Laurent',trend:[32,37,34,44,41,51,58,55,68,73,78,86]},
  {id:'neon',title:'Neon District',display:'NEON<br>DISTRICT',type:'Series',genres:['Thriller','Sci-Fi'],date:'2027-10-08',runtime:'8 episodes',image:'./assets/neon.webp',hero:'./assets/neon.webp',color:'cyan',tagline:'Every secret leaves a signal.',description:'A missing-persons investigator discovers that an entire neighborhood has vanished from the city’s digital memory. In a metropolis that never forgets, someone has found a way to disappear.',score:78,change:8,signals:[83,76,70],interest:81,discussion:'18.2K',pace:'+12%',director:'Mika Sato',trend:[30,36,40,38,47,45,56,59,65,62,72,78]},
  {id:'orbit',title:'Orbit Nine',display:'ORBIT<br>NINE',type:'Movie',genres:['Sci-Fi','Drama'],date:'2027-12-03',runtime:'2h 16m',image:'./assets/orbit.webp',hero:'./assets/orbit.webp',color:'blue',tagline:'The longest journey is the one home.',description:'An astronaut receives a transmission from her own voice, sent nine years into the future. With every orbit, the message changes—and the way home moves further out of reach.',score:91,change:16,signals:[94,90,86],interest:95,discussion:'32.6K',pace:'+24%',director:'Elena Park',trend:[36,39,49,46,53,63,59,68,76,81,86,91]},
  {id:'velvet',title:'Velvet Hour',display:'VELVET<br>HOUR',type:'Movie',genres:['Romance','Drama'],date:'2027-09-24',runtime:'1h 49m',image:'./assets/velvet.webp',hero:'./assets/velvet.webp',color:'rose',tagline:'One summer. Two almost-strangers.',description:'Two former friends meet by chance in a quiet coastal town. Over seven sunset walks, they try to decide whether the life they imagined together still belongs to them.',score:67,change:5,signals:[60,81,63],interest:73,discussion:'8.4K',pace:'+7%',director:'Luca Moreau',trend:[35,37,39,44,42,48,46,54,58,55,62,67]},
  {id:'hollow',title:'The Hollow',display:'THE<br>HOLLOW',type:'Series',genres:['Thriller','Mystery'],date:'2027-10-29',runtime:'6 episodes',image:'./assets/hollow.webp',hero:'./assets/hollow.webp',color:'green',tagline:'The forest knows your name.',description:'A botanist returns to the village where her sister disappeared and finds a cabin that appears on no map. Each night, a light in its window moves one tree closer.',score:59,change:-3,signals:[74,58,46],interest:64,discussion:'12.1K',pace:'−4%',director:'Nora Vale',trend:[47,53,51,58,62,61,66,63,61,64,62,59]},
  {id:'redline',title:'Redline Tokyo',display:'REDLINE<br>TOKYO',type:'Movie',genres:['Action','Thriller'],date:'2027-11-05',runtime:'2h 04m',image:'./assets/redline.webp',hero:'./assets/redline.webp',color:'red',tagline:'One city. One night. No brakes.',description:'A retired getaway driver takes one last delivery across Tokyo, only to discover that every traffic light in the city is being controlled by someone who wants him dead.',score:82,change:10,signals:[88,79,72],interest:87,discussion:'21.3K',pace:'+16%',director:'Ren Okada',trend:[32,35,41,39,51,56,53,61,70,73,78,82]}
];
window.CINEPULSE_IMPRESSIONS = [
 {id:'sample-1',name:'Maya',handle:'@mayainframes',initial:'M',film:'orbit',color:'lavender',text:'A voice message from your future self? That premise alone has me seated. Please let this be as thoughtful as it looks.',rating:5,ago:'2h ago'},
 {id:'sample-2',name:'Arjun',handle:'@thelastrow',initial:'A',film:'dunes',color:'peach',text:'The scale. The silence. That eclipse. If the story lives up to the atmosphere, this could be something special.',rating:4,ago:'4h ago'},
 {id:'sample-3',name:'Sofia',handle:'@softfocus',initial:'S',film:'velvet',color:'mint',text:'A small story with a big heart is always my kind of cinema. Quietly my most anticipated of the collection.',rating:5,ago:'5h ago'}
];
